#!/usr/bin/env perl

use 5.010;
use strict;
use warnings;

use Getopt::Long qw(:config bundling no_ignore_case auto_version auto_help);
use Module::List qw(list_modules);
use Module::Load;

my $num = 1;
my $list;
GetOptions(
    'n=i' => \$num,
    'l=s' => \$list,
);

my $mods = list_modules("Games::Word::Wordlist::",
                        {list_modules=>1, recurse=>1});
my @mods = keys %$mods;
die "Can't find any Games::Word::Wordlist::* modules, please install some\n"
    unless @mods;
my $mod;
if ($list) {
    $mod = "Games::Word::Wordlist::$list";
} else {
    $mod = $mods[rand @mods];
}

say $mod;
load $mod;
my $wl = $mod->new;

for (1..$num) {
    say $wl->random_word();
}
