#!/usr/bin/env perl

use strict;
use warnings;
use CDB_File;

if (@ARGV != 2 || $ARGV[0] =~ /^(-h|-\?|--help)$/) {
    print "$0 - List keys in a CDB file matching a regex (sorted)\n";
    print "Usage: $0 <cdb-name> <regex>\n";
    exit 0;
}

my $re;
eval { $re = qr/$ARGV[1]/ };
die "Invalid regex: $re: $@\n" if $@;

tie my(%h), 'CDB_File', $ARGV[0];

print map {"$_\n"} grep {$_ =~ $re} sort keys %h;
