#!/usr/bin/env perl

# "dzil build" creates build directory and tarballas in the project root dir.
# this clutters things. run this to clean the build files ("dzil clean" is the
# same but with slower startup overhead).

use 5.010;
use strict;
#use warnings;

BEGIN { $::Log_Level = 'info' }

my $dry = $ENV{DRY} || $ENV{DRYRUN} || $ENV{DRY_RUN};

open my($fh), "<", "dist.ini"
    or die "Can't open dist.ini in current dir\n";

my $name;
while (<$fh>) {
    /^\s*name\s*=\s*(\S.+?)\s*$/ and do {
        $name = $1;
        last;
    };
}
defined($name)
    or die "Can't get dist name from dist.ini\n";

for (glob("$name-[0-9]*"), glob(".build/*")) {
    print $dry ? "(DRY) ":"";
    print "Deleting $_ ...\n";
    next if $dry;
    system "rm", "-rf", $_;
}
