#!/usr/bin/env perl

use strict;
use warnings;
#use Log::Any::App;
#use Log::Any::For::Builtins qw(system);

use List::Util qw(first shuffle);
use SHARYANTO::Array::Util qw(split_array);

if (@ARGV < 2) { die "Usage: $0 <cmd> [cmd_opts] -- <arg> ...\n" }

my $cmd = shift @ARGV;
my ($cmd_opts, $args);
if (first {$_ eq '--'} @ARGV) {
    ($cmd_opts, $args) = split_array('--', \@ARGV, 2);
} else {
    $cmd_opts = [];
    $args = [@ARGV];
}
$args = [shuffle @$args];

system $cmd, @$cmd_opts, @$args;
