#!/usr/bin/env perl

# 2005-12-25

use 5.010;

if (@ARGV) {
    @files = @ARGV;
} else {
    @files = (<*.wma>);
}

for (@files) {
  if (-f "$_.mp3") {
    say "WARNING: $_.mp3 exists, skipped";
  }
  $esc = esc($_);
  #$cmd = "ffmpeg -i $esc -ab 128k $esc.mp3 && rm -f $esc";
  $cmd = "ffmpeg -i $esc -ab 128k $esc.mp3";
  say $cmd;
  system $cmd;
}

sub esc {
  local $_ = shift;
  s/'/'"'"'/g;
  "'$_'";
}
