#!/bin/bash

# doesn't work
#list-perl-releases --det --json | fsql --add-json - -F YEAR -F WEEKOFYEAR 'SELECT YEAR(date) || "w" || WEEKOFYEAR(date) week, COUNT(*) FROM stdin GROUP BY week ORDER BY week' -f text

list-perl-releases --det --json | fsql --add-json - -F YEAR -F WEEKOFYEAR 'SELECT YEAR(date) year, WEEKOFYEAR(date) week, COUNT(*) FROM stdin GROUP BY year,week ORDER BY year,week' -f text
