#!/usr/bin/perl

use 5.010;
use strict;
use warnings;

use Org::Parser;

my $org = Org::Parser->new;
my $doc;
{
    local $/;
    $doc = $org->parse(~~<>);
}

my $n = 0;
$doc->walk(
    sub {
        my $el = shift;
        $n++ if $el->isa('Org::Element::Headline') &&
            $el->is_todo && !$el->is_done;
    });

say $n;
