#!/bin/bash

# doesn't work
#list-my-perl-releases --det --json | fsql --add-json - -F YEAR -F WEEKOFYEAR 'SELECT YEAR(date) || "w" || WEEKOFYEAR(date) week, COUNT(*) FROM stdin GROUP BY week ORDER BY week' -f text

list-my-perl-releases --det --json | fsql --add-json - -F YEAR -F ISO_YEARWEEK 'SELECT ISO_YEARWEEK(date) week, COUNT(*) FROM stdin GROUP BY week ORDER BY week' -f text
