#!/usr/bin/env perl

use 5.010;
use strict;
use warnings;
#use Log::Any::App;

#die "Usage: $0 <sqlfile>\n" unless (@ARGV == 1);
#my $sqlfile = $ARGV[0];

#open my($sqlfh), "<", $sqlfile or die "Can't open $sqlfile: $!";

my ($pertblfile, $pertblfh, $prevtbl, $curtbl);
#while (<$sqlfh>) {
while (<>) {
    if (/^(?:CREATE TABLE) `(.+)`/) {
        $prevtbl = $curtbl;
        $curtbl = $1;
        #$pertblfile = "$sqlfile.$curtbl";
        $pertblfile = "$curtbl";

        if (defined $prevtbl) {
            close $pertblfh;
            #say "Finished writing $pertblfile";
        }
        say "Writing $pertblfile ...";
        open $pertblfh, ">", $pertblfile or die "Can't open $pertblfile: $!";
    }
    next unless $curtbl;
    print $pertblfh $_;
}
