#!/usr/bin/env perl

use 5.010;
use strict;
use warnings;

use DBI;

# find firefox profile directory, probably can be turned into a module as well,
# we need to parse profiles.ini
my $profile_dir;
{
    my @dirs = glob "$ENV{HOME}/.mozilla/firefox/*.default";
    die "Can't find any *.default dir in ~/.mozilla/firefox/" unless @dirs;
    warn "There are multiple *.default dirs in ~/.mozilla/firefox, picking ".
        "the first one" if @dirs > 1;
    $profile_dir = $dirs[0];
}

my $path = "$profile_dir/places.sqlite";
die "Can't find $path" unless -f $path;

my $dbh = DBI->connect("dbi:SQLite:dbname=$path", "", "", {RaiseError=>1});
my $sth = $dbh->prepare("SELECT url FROM moz_places ORDER BY last_visit_date");
$sth->execute;
while (my $row = $sth->fetchrow_hashref) {
    say $row->{url};
}

