#!/usr/bin/env perl

use 5.010;
use strict;
use warnings;

$^X =~ m!(.+/perlbrew/perls/[^/]+)/bin/perl! or
    die "current perl doesn't seem to be from perlbrew\n";

my $libdir = "$1/lib/site_perl";
my $i = 0;
while (-d "$libdir.$i") {
    $i++;
}
rename "$libdir", "$libdir.$i";
mkdir "$libdir";
