#!/usr/bin/env perl

use v5.14;
use strict;
use warnings;

use List::Util::Uniq qw(pushuniq);
use Perinci::CmdLine::Any;

our %SPEC;

$SPEC{extract_shopee_receipt_no_from_order_page} = {
    v => 1.1,
    args => {
        text => {
            schema => 'str*',
            cmdline_src => 'stdin_or_files',
        },
    },
};
sub extract_shopee_receipt_no_from_order_page {
    my %args = @_;

    my @receipt_ids;
    while ($args{text} =~ /^(?:Drop off|Pick ?up)\R(\S+)/img) {
        pushuniq @receipt_ids, $1;
    }

    [200, "OK", \@receipt_ids];
}

Perinci::CmdLine::Any->new(
    url => '/main/extract_shopee_receipt_no_from_order_page',
)->run;
