#!/usr/bin/env perl

use 5.010;
use strict;
use warnings;

use Data::Format::Pretty qw(format_pretty);

unless (@ARGV == 1) {
    print <<_;
Usage: $0 <data-in-perl-syntax>

Example:
 $0 '[{name=>"Bob", age=>38}, {name=>"Alice", age=>17}]'
_
    exit 1;
}

my $data = eval $ARGV[0];
die $@ if $@;

my $mod = "Console";
if ($0 =~ /-json/) {
    $mod = "JSON";
} elsif ($0 =~ /-yaml/) {
    $mod = "YAML";
}
print format_pretty($data, {module=>$mod});
