#!/usr/bin/env perl

use 5.010;
use strict;
use warnings;

use Authen::Passphrase::BlowfishCrypt;
use Perinci::CmdLine::Any;

our %SPEC;
$SPEC{gen_bc_password} = {
    v => 1.1,
    args => {
        cost => {
            schema => ['int*' => default => 8],
        },
        pass => {

        },
    },
};
sub gen_bc_password {
    my %args = @_;

    my $pass = $args{pass} //
        join("", map {("A".."Z", "a".."z")[52*rand()]} 1..10) .
            int(rand()*9000 + 1000);
    my $ppr = Authen::Passphrase::BlowfishCrypt->new(
        cost=>$args{cost},
        salt_random=>1,
        passphrase=>$pass,
    );

    [200, "OK", {pass=>$pass, hash=>$ppr->as_crypt}];
}

Perinci::CmdLine::Any->new(url=>'/main/gen_bc_password')->run;
