#!/usr/bin/env perl

use strict;
use warnings;

use ParseCron;
my $cron = ParseCron->new;

while (<>) {
    if (/^(\s*)([^#]\S*\s+\S+\s+\S+\s+\S+\s+\S+)\s+.+/) {
        print "$1# HUMAN TRANSLATION: ", $cron->parse_cron($2), "\n";
    }
    print;
}
