#!/usr/bin/env perl

use 5.010;
use strict;
use warnings;

say "This week:";
system "list-my-perl-releases-this-week", "--new", "--detail";

say "";
say "Last week:";
system "list-my-perl-releases-last-week", "--new", "--detail";

my $i = 2;
my $limit = $ARGV[0] // 3;
while ($i <= $limit) {
    say "";
    say "$i weeks ago:";
    system "list-my-perl-releases-n-weeks-ago", $i, "--new", "--detail";
    $i++;
}
