#!/usr/bin/env perl

use 5.010;
use strict;
use warnings;

use IPC::System::Options 'system', -die=>1;

system "norepeat --daily -- cpanm -n Locale::Codes";

require Locale::Codes::Country_Codes;
my $id2names = $Locale::Codes::Data{'country'}{'id2names'};
my @res;
for (grep {/\A\d+\z/} keys %$id2names) {
    my $shortest = [sort {length($a)<=>length($b)} @{ $id2names->{$_} }]->[0];
    push @res, lc $shortest;
}
say for @res;
