#!/usr/bin/env perl

use 5.010;
use strict;
use warnings;

use Module::List qw(list_modules);

#if (!@ARGV) {
#    die "Usage: $0 [prefix]\n";
#}

my $prefix = $ARGV[0] // '';
$prefix .= "::" unless !length($prefix) || $prefix =~ /::$/;
my $res = list_modules($prefix, {list_modules=>1, recurse=>1});
for my $k (sort keys %$res) {
    print "$k\n";
}
