#!/usr/bin/env perl

# FRAGMENT id=bash-completion-prog-hints command=list-perl-releases    

use DateTime;
my $today = DateTime->today(time_zone => $ENV{TZ});
system "list-perl-releases", "--date", $today->ymd, @ARGV;
