#!/usr/bin/env perl

# FRAGMENT id=shcompgen-hint command=list-perl-releases    

use DateTime;
use Log::Any::For::Builtins qw(system);

die "Usage: $0 <n> ...\n" unless @ARGV;
my $n = shift @ARGV;

my $today = DateTime->today(time_zone => $ENV{TZ});
my $start = $today->clone->subtract(days => $today->day_of_week-1); # start of this week
my $a = $start->clone->subtract(days => 7 + 7*($n-1)); # start of last n week
my $b = $start->clone->subtract(days => 1 + 7*($n-1)); # end   of last n week
system "list-perl-releases", "--date-min", $a->ymd, "--date-max", $b->ymd,
    @ARGV;
