#!/usr/bin/env perl

use DateTime;
my $today = DateTime->today;
my $start = $today->clone;
$start->set(day => 1);
system "list-perl-releases", "--date-min", $start->ymd, "--date-max", $today->ymd, @ARGV;
