#!/usr/bin/env perl

use 5.010;
use strict;
use warnings;

open my($fh), "<", "$ENV{HOME}/.bash_history";

my %n;
while (<$fh>) {
    next if /^#\d+$/; # timestamp
    s/\s.*//s;
    # XXX strip ENV=foo ENV2=bar ...
    $n{$_}++;
}

print "$_\t$n{$_}\n" for (sort {$n{$b}<=>$n{$a}} keys %n);
