#!/usr/bin/env perl

# FRAGMENT id=bash-completion-prog-hints command=list-perl-releases    

use DateTime;
use Log::Any::For::Builtins qw(system);

die "Usage: $0 <n> ...\n" unless @ARGV;
my $n = shift @ARGV;

my $today = DateTime->today(time_zone => $ENV{TZ});
my $day   = $today->clone->subtract(days => $n);
system "list-perl-releases", "--date", $day->ymd, @ARGV;
