#!/usr/bin/env perl

use 5.010;
use strict;
use warnings;

$^X =~ m!(.+/perlbrew/perls/[^/]+)/bin/perl! or
    die "current perl doesn't seem to be from perlbrew\n";

my $libdir = "$1/lib/site_perl";

(-d $libdir) or die "Can't find $libdir\n";
(-d "$libdir.0") and die "$libdir.0 already exists\n";

rename $libdir, "$libdir.0";
