#!/usr/bin/env perl

use 5.010;
use strict;
use warnings;

use Data::Dump;
use Data::Sah::Normalize qw(normalize_schema);
use YAML::XS;

my $yaml = do { local $/; ~~<> };
dd(normalize_schema(Load($yaml)));

