#!/usr/bin/env perl

# NO_PWP_RINCI

# DATE
# VERSION

use 5.010;
use strict;
use warnings;

our %SPEC;

$SPEC{app} = {
    v => 1.1,
    summary => 'Test default dry-run mode',
    description => <<'_',

This command by default runs in dry-run mode. To disable dry-run mode, either
specify `--no-dry-run` or `DRY_RUN=0`.

_
    args => {
    },
    features => {
        dry_run => {default=>1},
    },
};
sub app {
    my %args = @_;

    #use DD; dd \%args;

    [200, "OK", "dry-run mode is ".($args{-dry_run} ? "on" : "OFF")];
}

use Perinci::CmdLine::Any;
Perinci::CmdLine::Any->new(
    url=>'/main/app',
)->run;

# ABSTRACT:
# PODNAME:

=head1 SYNOPSIS

=cut
