#!/usr/bin/env perl

# NO_PWP_RINCI

# DATE
# VERSION

use 5.010;
use strict;
use warnings;

our %SPEC;

$SPEC{hasharg} = {
    v => 1.1,
    summary => 'A function that accepts a hash argument',
    description => <<'_',

Just a dummy description. Just a dummy description. Yup, just a dummy
description. Just a dummy description. Just a dummy description. Yeah, just a
dummy description. Just a dummy description.

_
    args => {
        names => {
            'x.name.is_plural' => 1,
            'x.name.singular' => 'name',
            schema => ['hash*', of=>'str*'],
            req => 1,
            pos => 0,
            greedy => 1,
        },
    },
};
sub hasharg {
    my %args = @_;

    [200, "OK", \%args];
}

use Perinci::CmdLine::Any;
Perinci::CmdLine::Any->new(
    url=>'/main/hasharg',
)->run;

# ABSTRACT:
# PODNAME:

=head1 SYNOPSIS

=cut
