#!/bin/bash

# created: 2014-09-05

# to be safe, try adding -d first

perlmv -e'
    $ext = ""; $ext = $1 if (-f $_) && s/\.(\w{3,4})$//;
    $_ = lc;
    if (/(.+)[.\( ]*(19\d\d|20\d\d)[\) ]*/) {
        # contains year, clean whatever after year
        $_="$1 ($2)";
    }
    s/\./ /g;
    s/[\(\[] \(/(/;
    s/^\[.+?\]//g;
    s/ {2,}/ /g;
    $_ .= ".$ext" if $ext;
' "$@"


