#!/usr/bin/env perl

use 5.010;
use strict;
use warnings;

use Perinci::CmdLine::Any;

BEGIN {
    $ENV{LOG} = 1;
    $ENV{LOG_LEVEL} = 'trace';
    $ENV{LOG_SAH_VALIDATOR_CODE} = 1;
}

our %SPEC;

$SPEC{gen_validator} = {
    v => 1.1,
    args => {
        schema => {schema=>'str*', req=>1, pos=>0, cmdline_src=>'file'},
        return_type => {schema=>['str*', in=>[qw/bool str full/]], default=>'bool'},
    },
    result_naked => 1,
};
sub gen_validator {
    require Data::Sah;
    require YAML::XS;

    my %args = @_;

    my $v = Data::Sah::gen_validator(
        YAML::XS::Load($args{schema}),
        {return_type=>$args{return_type}},
    );
    undef;
}

Perinci::CmdLine::Any->new(url => '/main/gen_validator')->run;
