#!/usr/bin/env perl

use 5.010;
use lib '/home/steven/proj/spanel/lib/perl';
use spanel::api::plan;
use YAML::XS;

if (@ARGV) {
    say Dump(spanel::api::plan::_parse($ARGV[0]));
} else {
    say "Usage: $0 <nama-file-yaml>";
    exit 1;
}
