#!/usr/bin/env perl

# dipakai utk menerima hasil copy paste transaksi dari ledger, lalu menjumlah
# semua angka yang ada di depan IDR.

use 5.010;
use strict;
use warnings;

my $tot = 0;
while (<>) {
    while (/(-?\d+) \s*IDR/g) {
        say "# detected $1" if $ENV{DEBUG};
        $tot += $1;
    }
}

say $tot;
