#!/usr/bin/env perl

# dipakai utk menerima hasil copy paste transaksi dari ledger, lalu menjumlah
# semua angka yang ada di depan IDR.

use 5.010;
use strict;
use warnings;

use Number::Format;
use Parse::Number::EN qw(parse_number_en $Pat);

my $occurrences = 0;
my $tot = 0;
my $output = '';
while (<>) {
    s/($Pat)( \s*IDR)/$occurrences++; $tot += parse_number_en(text=>$1); "\e[32m$1\e[0m$2"/eg;
    $output .= $_;
}

print $output;
say "===============";
say "Number of IDR numbers found: $occurrences";
say "Total: ", Number::Format->new->format_number($tot), " IDR";
