#!/usr/bin/env perl

# dipakai utk menerima hasil copy paste transaksi dari ledger, lalu menjumlah
# semua angka yang ada di depan IDR.

use 5.010;
use strict;
use warnings;

use Parse::Number::EN qw(parse_number_en $Pat);

my $tot = 0;
while (<>) {
    while (/($Pat) \s*IDR/g) {
        say "# detected $1" if $ENV{DEBUG};
        $tot += parse_number_en(text => $1);
    }
}

say $tot;
