#!/usr/bin/env perl

use 5.010;
use strict;
use warnings;

use Sys::Info;
use Sys::Info::Constants qw( :device_cpu );
my $info = Sys::Info->new;
my $cpu  = $info->device( CPU => {} );

Example:

printf "CPU: %s\n", scalar($cpu->identify)  || 'N/A';
printf "CPU speed is %s MHz\n", $cpu->speed || 'N/A';
printf "There are %d CPUs\n"  , $cpu->count || 1;
printf "CPU load: %s\n"       , $cpu->load  || 0;

#use Data::Dump;
#dd $cpu;

use Data::Dump;
dd [$cpu->identify];
