#!/usr/bin/env perl

use strict;
use warnings;
use Logfile::Tail::Timestamp;
use Time::HiRes 'sleep';

die "Usage: $0 '<wildcard-pattern>'\n" unless @ARGV == 1;

my $tail = Logfile::Tail::Timestamp->new(globs => [$ARGV[0]]);
while (1) {
    my $line = $tail->getline;
    if (defined $line) {
        print $line;
    } else {
        sleep 0.1;
    }
}
