#!/usr/bin/env perl

use 5.010;

package MyApp;
use Moo;
with 'Term::App::Role::Attrs';
use Data::Dump;

sub run {
    my $self = shift;

    dd {
        use_utf8      => $self->use_utf8,
        use_box_chars => $self->use_box_chars,
        interactive   => $self->interactive,
        use_color     => $self->use_color,
        color_depth   => $self->color_depth,
        term_width    => $self->term_width,
        term_height   => $self->term_height,
        _term_attrs_debug_info => $self->_term_attrs_debug_info,
    };
}

package main;
MyApp->new->run;
