#!/usr/bin/env perl

use strict;
use warnings;

use Perinci::CmdLine::Any;
use Sah::PSchema::perl::modname;

our %SPEC;

$SPEC{app} = {
    v => 1.1,
    args => {
        mod => {
            schema => Sah::PSchema::perl::modname->get_schema({ns_prefix=>'WordList'}, {req=>1}),
            req => 1,
            pos => 0,
        },
    },
};
sub app {
    my $args = {@_};
    [200, "OK", {schema=>$SPEC{app}{args}{mod}{schema}, arg=>$args->{mod}}];
}

Perinci::CmdLine::Any->new(url => '/main/app')->run;
