#!/usr/bin/env perl

use Getopt::Long::More;

Getopt::Long::More::Configure('auto_help', 'auto_version');
GetOptions(
    'fruit=s' => optspec(
        handler => \$opts{fruit},
        completion => [qw/apple apricot banana/],
        summary => 'Supply name of fruit to order',
    ),
    'amount|n=i' => optspec(
        handler => \$opts{amount},
        completion => sub {
            require Complete::Util;
            my %args = @_;
            Complete::Util::complete_array_elem(
                word => $args{word},
                array => [1..20],
            );
        },
        summary => 'Supply amount of fruits to order',
    ),
    'debug' => \$opts{debug},
    '<>' => optspec(
        handler => sub{},
        completion => [qw/a b c d/],
    ),
);

print "You ordered: $opts{fruit}\n";
