#!/usr/bin/env perl

# created: 2014-07-19

unless (@ARGV >= 2) {
    print <<'_';
Usage example: testcomp 'cmd --^' somecmd ...

This will set COMP_LINE to 'cmd --' and COMP_POINT to 6 (from the position of
the caret, which will then be stripped from COMP_LINE. After that, it will
execute somecmd.

So, this script adds convenience compared to counting COMP_POINT manually.
_
    exit 0;
}

my $comp_line  = shift @ARGV;
my $comp_point = index($comp_line, '^');
die "Please put a caret (^) somewhere in the comp_line to indicate comp_point\n"
    unless $comp_point >= 0;
$comp_line =~ s/\^//;

$ENV{PERL5OPT} = "-MLog::Any::App" . ($ENV{PERL5OPT} ? " $ENV{PERL5OPT}" : "");
$ENV{TRACE}    = 1;

$ENV{COMP_LINE}  = $comp_line;
$ENV{COMP_POINT} = $comp_point;

exec @ARGV
