#!/usr/bin/env perl

use strict;
use warnings;

use Encode::Simple;

binmode STDOUT, ":utf8";
for my $arg (@ARGV) {
    my $str = decode 'UTF-8', $arg;
    for (split //, $str) {
        printf "%s(%x) ", $_, ord($_);
    }
    print "\n";
}
