#!/usr/bin/env perl

use 5.010;

$|++;
for $module (@ARGV) {

	eval qq{require $module;};
	if ($@) {
		$err = $@;
	} else {
		($file = $module) =~ s#::#/#g;
		$file .= ".pm";
		say $INC{$file};
	}

}
